trigger:
  - main
  - v*

jobs:
  - job: "Python_Tests"
    pool:
      vmImage: "ubuntu-latest"
    strategy:
      matrix:
        py38:
          python.version: "3.8"
        py36:
          python.version: "3.6"
    displayName: "Python unit tests: "

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
      - bash: |
          python -m pip install --upgrade pip setuptools wheel
        displayName: "Install tools"
      - bash: |
          python -m pip install .[all]
          python -m pip install pytest-azurepipelines
        displayName: "Install package and dependencies"
      - bash: |
          python -m pytest --cov-report=html --test-run-title="pytest $(python.version)"
        displayName: "pytest"

  - job: "Python_Editable_Install_Tests"
    pool:
      vmImage: "ubuntu-latest"
    strategy:
      matrix:
        py38:
          python.version: "3.8"
        py36:
          python.version: "3.6"
    displayName: "Python install tests: "

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
      - bash: |
          python -m pip install --upgrade pip setuptools wheel
        displayName: "Install tools"
      - bash: |
          python -m pip install -e .[all]
        displayName: "Install package in editable mode"
      - bash: |
          python -c "import starter; print(starter.utils.io.read_yaml)"
        displayName: "Import test"
